config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_for :users

  root :to => "homes#top"
  get "home/about" => "homes#about"

  resources :books, only: [:index, :show, :edit, :create, :destroy, :update] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  
  resources :users, only: [:index, :show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get "followings" => "relationships#followings"
    get "followers" => "relationships#followers"
  end
  
  get "searches" => "searches#search"
  
  resources :groups, except: [:destroy] do
    resource :group_users, only: [:create, :destroy]
    get "new_mail" => "groups#new_mail"
    get "send_mail" => "groups#send_mail"
  end
  
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_users
  has_many :users, through: :group_users
  
  has_one_attached :image
  
  validates :name, presence: true
  validates :introduction, presence: true, length: { maximum: 200 }
  
  def get_image
    (image.attached?) ? image : 'no_image.jpg'
  end
  
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :is_matching_login_user, only: [:edit, :update]
  
  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    @group.owner_id = current_user.id
    if @group.save
      redirect_to groups_path
    else
      render :new
    end
  end

  def index
    @book = Book.new
    @groups = Group.all
  end
  
  def edit
    @group = Group.find(params[:id])
  end

  def update
    @group = Group.find(params[:id])
    if @group.update(group_params)
      redirect_to groups_path
    else
      render :edit
    end
  end

  def show
    @group = Group.find(params[:id])
  end
  
  def new_mail
    @group = Group.find(params[:group_id])
  end
  
  def send_mail
    # 宛先
    @group = Group.find(params[:group_id])
    @group_users = @group.group_users.joins(:user)
    @email_list = @group_users.pluck(:email)
    # タイトル
    @title = params[:title]
    # 本文
    @content = params[:content]
    # ActionMailer実行
    EventMailer.send_mail(@email_list, @title, @content).deliver
    
  end
    
  private
  
  def group_params
    params.require(:group).permit(:name, :introduction, :image)
  end
  
  def is_matching_login_user
    owner_id = Group.find(params[:id]).owner_id.to_i
    login_user_id = current_user.id
    if owner_id != login_user_id
      redirect_to groups_path
    end
  end
  
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h1>Editing Group</h1>
      <%= render 'layouts/errors', obj: @group %>
      <%= form_with model: @group, local: true do |f| %>
        <div class="form-group">
          <%= f.label :name, 'グループ名' %>
          <%= f.text_field :name, class: 'form-control book_title' %>
        </div>
        <div class="form-group">
          <%= f.label :introduction, '紹介文' %>
          <%= f.text_area :introduction, class: 'form-control book_body' %>
        </div>
        <div class="form-group">
          <%= f.label :image, 'グループ画像' %>
          <%= f.file_field :image, class: "form-control-file user_image", accept: 'image/*' %>
        </div>
        <div class="form-group">
          <%= f.submit class: 'btn btn-info' %>
        </div>
      <% end %>
      <%= link_to 'Back', users_path, class: "back" %>
  </div>
</div>

app/views/groups/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: current_user %>
      
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Groups</h2>
      <table class='table'>
        <thead>
          <tr>
            <th></th>
            <th>グループ名</th>
            <th>紹介文</th>
            <th>メンバー数</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @groups.each do |group| %>
            <tr>
              <td>
                <%= image_tag group.get_image, size: '50x50' %>
              </td>
              <td>
                <%= link_to group_path(group) do %>
                  <%= group.name %>
                <% end %>
              </td>
              <td>
                <%= group.introduction %>
              </td>
              <td>
                <%= group.group_users.count %>
              </td>
              <td>
                <% if group.owner_id == current_user.id %>
                  <%= link_to 'Edit', edit_group_path(group), class: 'btn btn-success' %>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/groups/new.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h1>Create Group</h1>
      <%= render 'layouts/errors', obj: @group %>
      <%= form_with model: @group, local: true do |f| %>
        <div class="form-group">
          <%= f.label :name, 'グループ名' %>
          <%= f.text_field :name, class: 'form-control book_title' %>
        </div>
        <div class="form-group">
          <%= f.label :introduction, '紹介文' %>
          <%= f.text_area :introduction, class: 'form-control book_body' %>
        </div>
        <div class="form-group">
          <%= f.label :image, 'グループ画像' %>
          <%= f.file_field :image, class: "form-control-file user_image", accept: 'image/*' %>
        </div>
        <div class="form-group">
          <%= f.submit class: 'btn btn-info' %>
        </div>
      <% end %>
      <%= link_to 'Back', users_path, class: "back" %>
  </div>
</div>

app/views/groups/new_mail.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h1>Event Mail</h1>
      <%= render 'layouts/errors', obj: @group %>
      <%= form_with url: group_send_mail_path(@group), local: true, method: :get do |f| %>
        <div class="form-group">
          <%= f.label :title %>
          <%= f.text_field :title, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :content %>
          <%= f.text_area :content, class: 'form-control' %>
        </div>
        <div class="form-group text-right">
          <%= f.submit '送信', class: 'btn btn-success' %>
        </div>
      <% end %>
      <%= link_to 'Back', group_path(@group), class: "back" %>
  </div>
</div>

app/views/groups/send_mail.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>送信が完了しました</h1>
      <p>内容は以下の通りです。</p>
      <table class="table table-bordered">
        <tr>
          <td class="bg-secondary text-white">グループ名</td>
          <td><%= @group.name %></td>
        </tr>
        <tr>
          <td class="bg-secondary text-white">宛先</td>
          <td>
            <table class="table table-borderless">
                <tr>
                  <th class="m-0 p-0">ユーザ名</th>
                  <th class="m-0 p-0">メールアドレス</th>
                </tr>
              <% @group_users.each do |group_user| %>
                <tr>
                  <td class="m-0 p-0"><%= group_user.user.name  %></td>
                  <td class="m-0 p-0"><%= group_user.user.email %></td>
                </tr>
              <% end %>
            </table>
          </td>
        </tr>
        <tr>
          <td class="bg-secondary text-white">タイトル</td>
          <td><%= @title %></td>
        </tr>
        <tr>
          <td class="bg-secondary text-white">本文</p>
          <td><%= safe_join(@content.split("\n"), tag(:br)) %></td>
        </tr>
      </table>
      <%= link_to "グループ詳細ページへ戻る", group_path(@group) %>
  </div>
</div>

app/views/groups/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: current_user %>
      
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Group Detail</h2>
      <table class='table'>
        <thead>
          <tr>
            <th></th>
            <th>グループ名</th>
            <th>紹介文</th>
            <th>メンバー</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>
              <%= image_tag @group.get_image, size: '50x50' %>
            </td>
            <td>
              <%= @group.name %>
            </td>
            <td>
              <%= @group.introduction %>
            </td>
            <td>
              <% @group.group_users.each do |group_user| %>
                <%= group_user.user.name %><br>
              <% end %>
            </td>
            <td>
              <% if @group.owner_id == current_user.id %>
                <%= link_to 'Edit', edit_group_path(@group), class: 'btn btn-success' %>
                <%= link_to 'Notice an Event', group_new_mail_path(@group), class: 'btn btn-info' %>
              <% else %>
                <% if @group.group_users.joined_by?(current_user) %>
                  <%= link_to 'Leave this group', group_group_users_path(@group), class: 'btn btn-danger', method: :delete %>
                <% else %>
                  <%= link_to 'Join this group', group_group_users_path(@group), class: 'btn btn-success', method: :post %>
                <% end %>
              <% end %>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>